# --- General options --- #

title: Priyadarshi Dey
description: Assistant Professor of Mathematics at Millsaps College

url: "https://deyp2025.github.io"
baseurl: ""

# --- Navigation bar options --- #

navbar-links:
  Publications: "publications"
  Talks: "talks"
  Teaching: "teaching"
  CV: "files/CV_PDey.pdf"

# --- Logo --- #

avatar: "/img/avatar-icon.jpg"
avatar-size: 160px

# --- Footer options --- #

author:
  name: Priyadarshi Dey

social-network-links:
  email: "deyp@millsaps.edu"
  github: deyp2025
  orcid: "0000-0002-1064-7735"

# --- General options --- #

height-of-header: navbar

# --- Ruby Date Format --- #

post-date-format: "%B %-d, %Y"

# --- Markdown --- #

markdown: kramdown

kramdown:
  input: GFM

# --- Sass/SCSS --- #

sass:
  sass_dir: _sass
  style: compressed

# --- Outputting --- #

permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: America/Chicago

# --- Plugins --- #

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-include-cache

# --- Jekyll --- #

exclude:
  - .babelrc
  - .dcignore
  - .eslintignore
  - .eslintrc
  - .node-version
  - .prettierignore
  - .prettierrc
  - .ruby-version
  - CONTRIBUTING
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package-lock.json
  - package.json
  - Procfile
  - Rakefile
  - README.md
  - tmp

include:
  - _redirects
  - _headers

# --- Collections --- #

collections:
  posts:
    output: true
    permalink: /blog/:year-:month-:day-:title/
  portfolio:
    output: true
    permalink: /:collection/:path/

# --- Defaults --- #

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
      show-avatar: true
  - scope:
      path: "_posts"
    values:
      layout: "post"
  - scope:
      path: "_portfolio"
    values:
      layout: "page"

# --- Tags --- #

link-tags: true

# --- Sitemap --- #

sitemap:
  changefreq: monthly
  priority: 0.7
  filename: sitemap.xml
